site_name: BGE and Senior Phase Computing Science
nav:
    - Home: 'index.md'
    - S1:
      - Home: BGE/index.md
      - Pyton Programming: 'BGE/S2/Intro_to_Python.md'
    - S2:
      - Home: BGE/S2/S2_index.md
      - Pyton Programming: 
        - Introduction to Python: 'BGE/S2/Python_Programming/1.0_Intro_to_Python.md'
        - Extra Credit Tasks: 'BGE/S2/Python_Programming/Extra_Credit_Tasks.md'
    - S3: 'BGE/S3/index.md'
    - Senior Phase: 
      - Home: 'Senior_Phase/index.md'
      
markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs

    

