site_name: Advanced Higher Computing Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - SDD/index.md
    - Unit 2 - Software Implementation:
      - SI/index.md
      - Insertion Sorts: 'SI/01-Insertation-Sorts.md' 
    - Unit 3 - Computer Systems:
      - CS/index.md
    - Unit 4 - Database Design and Development:
      - DDD/index.md
      
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.expand

