site_name: Advanced Higher Computing Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - SDD/index.md
      - Analysis: 
          - Explanation: 'SDD/1.0-Analysis-Explanation.md'
          - Functional Requirements: 'SDD/1.2-Functional-Requirements.md'
          - Feasability Studies: 'SDD/1.3-Feasability-Studies.md'
          - Project Planning: 'SDD/1.4-Project-Planning.md'
          - Requirement Specification: 'SDD/1.5-Requirement-Specification.md'  
      - Design:
          - Explanation: 'SDD/3.0-Design-Explanation.md'
      - Software Implementation:
          - Explanation: 'SDD/4.0-Software-Implementation-Explanantion.md'  
          - Parallel-1D-arrays: 'SDD/4.1-Parallel-1D-Arrays.md'  
          - Working-with-Records: 'SDD/4.2-Working-with-Records.md' 
          - Arrays-of-Records: 'SDD/4.3-Arrays-of-Records.md' 
          - Binary Search: 'SDD/4.4-Binary-Search.md'
          - Insertation Sorts: 'SDD/4.5-Insertation-Sorts.md'
          - OOP - Class: 'SDD/4.7-Class.md'
          - OOP - Objects: 'SDD/4.8-Objects.md'
    #- Unit 2 - Computer Systems:
      #- CS/index.md
    - Unit 3 - Database Design and Development:
      - DDD/index.md
    - Revision:
      - Revision/index.md
      - 1.0 - Question and Project Papers: 'Revision/1.0-Question-and-Project-Papers.md'
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html    
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs
    

