site_name: Advanced Higher Computing Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - SDD/index.md
      - Development Methodologies: 
          - Analysis: 'SDD/01-Analysis.md'
    - Unit 2 - Software Implementation:
      - SI/index.md
      - Parallel Arrays: 'SI/01-Parallel-1D-Arrays.md' 
      - Working with Records: 'SI/02-Working-with-Records.md' 
      - Arrays of Records: 'SI/03-Arrays-of-Records.md' 
      - Insertion Sort: 'SI/04-Insertation-Sorts.md'
    - Unit 3 - Computer Systems:
      - CS/index.md
    - Unit 4 - Database Design and Development:
      - DDD/index.md

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    

